### ISSUE TITLE
NullPointerException in Main @ Line 429

### ISSUE THREAD

**Issue by PyuuCH** [lvivtotoro/luapreproc#1]
So I tried a few different files, and none would compile due to an error at Line 429 of Main (which is OOLua.java)
```Lua
print("Hello World");
```
The above even errors out.
![image](https://cloud.githubusercontent.com/assets/13685109/21412500/60d9e7e0-c7b6-11e6-9dda-7d2f85629e78.png)

**Comment by PyuuCH** [comment]
Additionally, this crash only applies to Version 1.1, and 1.12 of this program. Version 1.0 doesn't error out at least.

**Comment by lvivtotoro** [comment]
The current latest commit fixes this issue, on version [1.13](https://www.mediafire.com/?2f4j5d8wbk8czpb).
